import { handle } from 'hono/vercel';
// Generated by `npm run build:api` (Vite + Vercel buildCommand).
// @ts-expect-error generated ESM bundle
import { createApp } from './_app.mjs';

/**
 * Catch-all so /api/health, /api/auth/login, etc. hit this function
 * without vercel.json rewrites (those caused an infinite reload loop).
 *
 * Set NODEJS_HELPERS=0 in Vercel env so POST /api/auth/login works.
 */
export const config = {
  maxDuration: 60,
  memory: 1024,
};

export default handle(createApp());
