import { handle } from '@hono/node-server/vercel';
// Generated by `npm run build:api` (and committed for Vercel packaging).
import { createApp } from './_app.mjs';

/**
 * Node runtime + @hono/node-server/vercel (not hono/vercel — that adapter is Edge-only
 * and hangs when Vercel passes IncomingMessage/ServerResponse).
 *
 * Set NODEJS_HELPERS=0 in Vercel env so POST /api/auth/login works.
 */
export const config = {
  runtime: 'nodejs',
  maxDuration: 60,
  memory: 1024,
};

export default handle(createApp());
