import { handle } from 'hono/vercel';
// Generated by `npm run build:api` (Vite + Vercel buildCommand).
// @ts-expect-error generated ESM bundle
import { createApp } from './_app.mjs';

/**
 * Set NODEJS_HELPERS=0 in Vercel Project → Environment Variables
 * so POST /api/auth/login is not blocked by the Node.js Helpers middleware.
 */
export const config = {
  maxDuration: 60,
  memory: 1024,
};

export default handle(createApp());
